version: '3.0'

services:
  sample-test:
    container_name: sample-test
    build:
      context: .
      dockerfile: Dockerfile-test
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=homologation
